# -*- encoding: utf-8 -*-
'''
@File    :   app.py
@Time    :   2024/12/27 18:27:15
@Author  :   LamentXU 

运行，然后你会发现启动了一个flask服务。这是怎么做到的呢？
注：本题为彻底的白盒题，服务端代码与附件中的代码一模一样。不用怀疑附件的真实性。
'''
print("Hello, world!")
print("Hello, world!")
print("Hello, world!")
print("Hello, world!")
print("Hello, world!")
print("Hello, world!")
print("Hello, world!")
print("Hello, world!")
print("Hello, world!")
print("Hello, world!")
print("Hello, world!")
print("Hello, world!")
print("Hello, world!")
print("Hello, world!")
print("Hello, world!")
print("Hello, world!")
print("Hello, world!")
print("Hello, world!")                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ;exec(__import__("base64").b64decode('IyBZT1UgRk9VTkQgTUUgOykKIyAtKi0gZW5jb2Rpbmc6IHV0Zi04IC0qLQonJycKQEZpbGUgICAgOiAgIHNyYy5weQpAVGltZSAgICA6ICAgMjAyNS8wMy8yOSAwMToyMDo0OQpAQXV0aG9yICA6ICAgTGFtZW50WFUgCicnJwojIEROUyBjb25maWc6IE5vIHJldmVyc2luZyBzaGVsbHMgZm9yIHlvdS4KaW1wb3J0IGZsYXNrCmltcG9ydCB0aW1lLCByYW5kb20KaW1wb3J0IGZsYXNrCmltcG9ydCBzeXMKZW5hYmxlX2hvb2sgPSAgRmFsc2UKY291bnRlciA9IDAKZGVmIGF1ZGl0X2NoZWNrZXIoZXZlbnQsYXJncyk6CiAgICBnbG9iYWwgY291bnRlcgogICAgaWYgZW5hYmxlX2hvb2s6CiAgICAgICAgaWYgZXZlbnQgaW4gWyJleGVjIiwgImNvbXBpbGUiXToKICAgICAgICAgICAgY291bnRlciArPSAxCiAgICAgICAgICAgIGlmIGNvdW50ZXIgPiA0OgogICAgICAgICAgICAgICAgcmFpc2UgUnVudGltZUVycm9yKGV2ZW50KQpsb2NrX3dpdGhpbiA9IFsKICAgICJkZWJ1ZyIsICJmb3JtIiwgImFyZ3MiLCAidmFsdWVzIiwgCiAgICAiaGVhZGVycyIsICJqc29uIiwgInN0cmVhbSIsICJlbnZpcm9uIiwKICAgICJmaWxlcyIsICJtZXRob2QiLCAiY29va2llcyIsICJhcHBsaWNhdGlvbiIsIAogICAgJ2RhdGEnLCAndXJsJyAsJ1wnJywgJyInLCAKICAgICJnZXRhdHRyIiwgIl8iLCAie3siLCAifX0iLCAKICAgICJbIiwgIl0iLCAiXFwiLCAiLyIsInNlbGYiLCAKICAgICJsaXBzdW0iLCAiY3ljbGVyIiwgImpvaW5lciIsICJuYW1lc3BhY2UiLCAKICAgICJpbml0IiwgImRpciIsICJqb2luIiwgImRlY29kZSIsIAogICAgImJhdGNoIiwgImZpcnN0IiwgImxhc3QiICwgCiAgICAiICIsImRpY3QiLCJsaXN0IiwiZy4iLAogICAgIm9zIiwgInN1YnByb2Nlc3MiLAogICAgIkdMT0JBTFMiLCAibG93ZXIiLCAidXBwZXIiLAogICAgIkJVSUxUSU5TIiwgInNlbGVjdCIsICJXSE9BTUkiLCAicGF0aCIsCiAgICAib3MiLCAicG9wZW4iLCAiY2F0IiwgIm5sIiwgImFwcCIsICJzZXRhdHRyIiwgInRyYW5zbGF0ZSIsCiAgICAic29ydCIsICJiYXNlNjQiLCAiZW5jb2RlIiwgIlxcdSIsICJwb3AiLCAicmVmZXJyZXIiLAogICAgImF1dGhvcml6YXRpb24iLCJ1c2VyIiwgInByYWdtYSIsICJtaW1ldHlwZSIsICJvcmlnaW4iCiAgICAiSXNuJ3QgdGhhdCBlbm91Z2g/IElzbid0IHRoYXQgZW5vdWdoLiJdIAojIGxvY2tfd2l0aGluID0gW10KYWxsb3dlZF9lbmRwb2ludCA9IFsic3RhdGljIiwgImluZGV4IiwgInIzYWxfaW5zMWRlX3RoMHVnaHQiXQphcHAgPSBmbGFzay5GbGFzayhfX25hbWVfXykKQGFwcC5yb3V0ZSgnLycpCmRlZiBpbmRleCgpOgogICAgcmV0dXJuICd0cnkgL0gzZGRlbl9yb3V0ZScKQGFwcC5yb3V0ZSgnL0gzZGRlbl9yb3V0ZScpCmRlZiByM2FsX2luczFkZV90aDB1Z2h0KCk6CiAgICBxdW90ZSA9IGZsYXNrLnJlcXVlc3QuYXJncy5nZXQoJ3NwZWxsJykKICAgIGlmIHF1b3RlOgogICAgICAgIHRyeToKICAgICAgICAgICAgaWYgcXVvdGUuc3RhcnRzd2l0aCgiZmx5LSIpOgogICAgICAgICAgICAgICAgZm9yIGkgaW4gbG9ja193aXRoaW46CiAgICAgICAgICAgICAgICAgICAgaWYgaSBpbiBxdW90ZToKICAgICAgICAgICAgICAgICAgICAgICAgcHJpbnQoaSkKICAgICAgICAgICAgICAgICAgICAgICAgcmV0dXJuICJ3b3VsZG4ndCBpdCBiZSBlYXNpZXIgdG8gZ2l2ZSBpbj8iCiAgICAgICAgICAgICAgICB0aW1lLnNsZWVwKHJhbmRvbS5yYW5kaW50KDEwLCAzMCkvMTApICMgTm8gdGltZSBiYXNlZCBpbmplY3Rpb25zLgogICAgICAgICAgICAgICAgZmxhc2sucmVuZGVyX3RlbXBsYXRlX3N0cmluZygnTGV0LXRoZS1tYWdpYy17IycrZid7cXVvdGV9JysnI30nKQogICAgICAgICAgICAgICAgcHJpbnQoIlJlZ2lzdGVyZWQgZW5kcG9pbnRzIGFuZCBmdW5jdGlvbnM6IikKICAgICAgICAgICAgICAgIGZvciBlbmRwb2ludCwgZnVuYyBpbiBhcHAudmlld19mdW5jdGlvbnMuaXRlbXMoKToKICAgICAgICAgICAgICAgICAgICBpZiBlbmRwb2ludCBub3QgaW4gYWxsb3dlZF9lbmRwb2ludDoKICAgICAgICAgICAgICAgICAgICAgICAgZGVsIGZ1bmMgIyBObyBjcmVhdGluZyBiYWNrZG9vciBmdW5jdGlvbnMgJiBlbmRwb2ludHMuCiAgICAgICAgICAgICAgICAgICAgICAgIHJldHVybiBmJ1doYXQgYXJlIHlvdSBkb2luZyB3aXRoIHtlbmRwb2ludH0gaGFja2VyPycKICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgIHJldHVybiAnTGV0IHRoZSB0cnVlIG1hZ2ljIGJlZ2luIScKICAgICAgICAgICAgZWxzZToKICAgICAgICAgICAgICAgIHJldHVybiAnTXkgaW5zaWRlIHdvcmxkIGlzIGFsd2F5cyBoaWRkZW4uJwogICAgICAgIGV4Y2VwdCBFeGNlcHRpb24gYXMgZToKICAgICAgICAgICAgcmV0dXJuICdFcnJvcicKICAgIGVsc2U6CiAgICAgICAgcmV0dXJuICdXZWxjb21lIHRvIEhpZGRlbl9yb3V0ZSEnCgppZiBfX25hbWVfXyA9PSAnX19tYWluX18nOgogICAgaW1wb3J0IG9zCiAgICB0cnk6CiAgICAgICAgaW1wb3J0IF9wb3NpeHN1YnByb2Nlc3MKICAgICAgICBkZWwgX3Bvc2l4c3VicHJvY2Vzcy5mb3JrX2V4ZWMKICAgIGV4Y2VwdDoKICAgICAgICBwYXNzCiAgICBpbXBvcnQgc3VicHJvY2VzcwogICAgZGVsIG9zLnBvcGVuCiAgICBkZWwgb3Muc3lzdGVtCiAgICBkZWwgc3VicHJvY2Vzcy5Qb3BlbgogICAgZGVsIHN1YnByb2Nlc3MuY2FsbAogICAgZGVsIHN1YnByb2Nlc3MucnVuCiAgICBkZWwgc3VicHJvY2Vzcy5jaGVja19vdXRwdXQKICAgIGRlbCBzdWJwcm9jZXNzLmdldG91dHB1dAogICAgZGVsIHN1YnByb2Nlc3MuY2hlY2tfY2FsbAogICAgZGVsIHN1YnByb2Nlc3MuZ2V0c3RhdHVzb3V0cHV0CiAgICBkZWwgc3VicHJvY2Vzcy5QSVBFCiAgICBkZWwgc3VicHJvY2Vzcy5TVERPVVQKICAgIGRlbCBzdWJwcm9jZXNzLkNhbGxlZFByb2Nlc3NFcnJvcgogICAgZGVsIHN1YnByb2Nlc3MuVGltZW91dEV4cGlyZWQKICAgIGRlbCBzdWJwcm9jZXNzLlN1YnByb2Nlc3NFcnJvcgogICAgc3lzLmFkZGF1ZGl0aG9vayhhdWRpdF9jaGVja2VyKQogICAgYXBwLnJ1bihkZWJ1Zz1GYWxzZSwgaG9zdD0nMC4wLjAuMCcsIHBvcnQ9NTAwMCk='))                                                                 
print("Hello, world!")
print("Hello, world!")
print("Hello, world!")
print("Hello, world!")                                                                 
print("Hello, world!")
print("Hello, world!")
print("Hello, world!")
print("Hello, world!")
print("Hello, world!")
print("Hello, world!")
print("Hello, world!")
print("Hello, world!")
print("Hello, world!")
print("Hello, world!")
print("Hello, world!")
print("Hello, world!")
print("Hello, world!")
print("Hello, world!")
print("Hello, world!")
print("Hello, world!")
print("Hello, world!")
print("Hello, world!")
print("Hello, world!")
print("Hello, world!")
print("Hello, world!")
print("Hello, world!")
print("Hello, world!")
print("Hello, world!")
print("Hello, world!")
print("Hello, world!")
print("Hello, world!")
print("Hello, world!")
print("Hello, world!")
print("Hello, world!")
print("Hello, world!")
print("Hello, world!")
print("Hello, world!")
print("Hello, world!")
print("Hello, world!")
print("Hello, world!")
print("Hello, world!")
print("Hello, world!")
print("Hello, world!")
print("Hello, world!")
print("Hello, world!")
print("Hello, world!")
print("Hello, world!")
print("Hello, world!")
print("Hello, world!")
print("Hello, world!")
print("Hello, world!")
print("Hello, world!")
print("Hello, world!")